### ISSUE TITLE
AutoPlant version support, plants problem

### ISSUE THREAD

**Issue by Testic19** [areinfranck/AutoPlant#3]
Hello, your plugin does not support 1.16 (it says on spigot that supports) version and i tried to use 5.4 version which supports 1.16.5, now i have problem, I can destroy plants but i have no drops from it, it only works if i enable block-break but players can destroy spawn then, i also added Extra Worldguard flags and i tried to use allow-block-break flag but it works only on worldguard 6, i really need help.

**Comment by areinfranck** [comment]
Hi there, thanks for using the plugin!

Unfortunately my plugin is limited to the functionality of WorldGuard itself, as it is the main dependency. The behavior you're explaining in this issue is expected from the plugin, and is outlined in the documentation on spigot itself which you can read [here](https://www.spigotmc.org/resources/autoplant-world-guard-dependency-v7-0-6.79720/).

The plugin functions properly when the given flags you have mentioned above are enabled, which grant your players the ability to break the blocks in that region and receive drops. Understanding that enabling block-break may allow players to destroy more than your intended areas, the best way to circumvent this issue is to define individual regions that are the exact dimensions of your farm, rather than a much larger area. This way, you can allow for full functionality of the plugin while only allowing your players to harvest crops.

I assume your issue is isolated to this behavior, however, if you are using a primitive version of the game, you should be sure to download the WorldGuard plugin from that version and not the most recent build (i.e the 1.16 version of AutoPlant works best with the 1.16 version of WorldGuard. 1.18 WorldGuard could hide some unexpected behaviors I did not encounter in testing).

**Comment by areinfranck** [comment]
No follow up, issue assumed to be resolved.
